# Generated by Django 6.0.5 on 2026-05-12 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionFitosanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=100)),
                ('lote', models.CharField(blank=True, max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='predios.predio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicación fitosanitaria',
                'verbose_name_plural': 'Aplicaciones fitosanitarias',
            },
        ),
        migrations.CreateModel(
            name='MonitoreoPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plaga', models.CharField(choices=[('trips', 'Trips'), ('acaros', 'Ácaros'), ('mosca_blanca', 'Mosca blanca'), ('otro', 'Otro')], max_length=50)),
                ('nivel_infestacion', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20)),
                ('fecha_monitoreo', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='predios.predio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitoreo de plaga',
                'verbose_name_plural': 'Monitoreos de plagas',
            },
        ),
    ]
