# Generated by Django 6.0.5 on 2026-05-12 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vencimiento_certificado', 'Vencimiento de certificado'), ('vencimiento_registro', 'Vencimiento de registro ICA'), ('monitoreo_pendiente', 'Monitoreo pendiente'), ('incumplimiento', 'Incumplimiento detectado')], max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('atendida', 'Atendida'), ('descartada', 'Descartada')], default='activa', max_length=20)),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='predios.predio')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
