# Generated by Django 6.0.5 on 2026-05-12 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_ica', models.CharField(max_length=200)),
                ('fecha_inspeccion', models.DateField()),
                ('resultado', models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('condicionada', 'Condicionada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='predios.predio')),
            ],
            options={
                'verbose_name': 'Inspección',
                'verbose_name_plural': 'Inspecciones',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificado', models.CharField(max_length=100, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='vigente', max_length=20)),
                ('inspeccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='inspecciones.inspeccion')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
