# Generated by Django 6.0.5 on 2026-05-12 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Fase del checklist',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Requisito fitosanitario')),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('norma_referencia', models.CharField(blank=True, max_length=200)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklist.fasechecklist')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('na', 'No aplica'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.itemchecklist')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_checklist', to='predios.predio')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de checklist',
                'unique_together': {('predio', 'item')},
            },
        ),
    ]
