# Generated by Django 6.0.5 on 2026-05-12 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('registro_ica', models.CharField(max_length=100, unique=True)),
                ('municipio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('vereda', models.CharField(blank=True, max_length=100)),
                ('hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estado_habilitacion', models.CharField(choices=[('habilitado', 'Habilitado'), ('suspendido', 'Suspendido'), ('en_proceso', 'En proceso de habilitación')], default='en_proceso', max_length=20)),
                ('fecha_vencimiento_registro', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPredio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], default='operador', max_length=20)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predios.predio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'predio')},
            },
        ),
        migrations.AddField(
            model_name='predio',
            name='usuarios',
            field=models.ManyToManyField(related_name='predios', through='predios.UsuarioPredio', to=settings.AUTH_USER_MODEL),
        ),
    ]
